#!/bin/sh
#
# Plugin to monitor the number of accesses to Apache servers. It handles
# a list of ports passed in from a plugin configuration file.
#
# By chlunde and mortehu 2006

#%# family=auto
#%# capabilities=autoconf

[ -z "$ports" ] && ports=80
[ -z "$url" ] && url='http://127.0.0.1:%d/server-status?auto'

if [ "$1" = "autoconf" ]
then
	test -x "`which wget`" || { echo no; exit 1; }
	for port in $ports
	do
		wget -q "`printf $url $port`" -O /dev/null || { echo "no (botched port $port)"; exit 1; }
	done
	echo yes
elif [ "$1" = "config" ]
then
	echo 'graph_title Apache accesses'
	echo 'graph_args --base 1000'
	echo 'graph_vlabel accesses / \${graph_period}'
	echo 'graph_category apache'

	for port in $ports
	do
		echo accesses$port.label port $port
		echo accesses$port.type DERIVE
		echo accesses$port.max 1000000
		echo accesses$port.min 0
	done
else
	for port in $ports
	do
		wget -q "`printf $url $port`" -O- | sed "/Total Accesses/!d;s/.*:/accesses$port.value/"
	done
fi
